[package]
name = "rs"
version = "0.1.0"
edition = "2021"

[lib]
# crate-type = ["cdylib"]
crate-type = ["staticlib"]

[dependencies]
anyhow = "1.0.81"
cxx = "1.0.120"
tokio-modbus = { version = "0.11.0", features = ["tcp-sync"] }

[build-dependencies]
cxx-build = "1.0"
